// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/ads.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ─── Request ────────────────────────────────────────────────────────────────
// top_n: how many ranked ads to return (e.g., top 10 for an auction slot)
// campaign_id: optional filter — 0 means "all campaigns"
type RankAdsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopN          int32                  `protobuf:"varint,1,opt,name=top_n,json=topN,proto3" json:"top_n,omitempty"`
	CampaignId    int32                  `protobuf:"varint,2,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RankAdsRequest) Reset() {
	*x = RankAdsRequest{}
	mi := &file_proto_ads_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RankAdsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankAdsRequest) ProtoMessage() {}

func (x *RankAdsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ads_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankAdsRequest.ProtoReflect.Descriptor instead.
func (*RankAdsRequest) Descriptor() ([]byte, []int) {
	return file_proto_ads_proto_rawDescGZIP(), []int{0}
}

func (x *RankAdsRequest) GetTopN() int32 {
	if x != nil {
		return x.TopN
	}
	return 0
}

func (x *RankAdsRequest) GetCampaignId() int32 {
	if x != nil {
		return x.CampaignId
	}
	return 0
}

// ─── Response ───────────────────────────────────────────────────────────────
type RankedAd struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AdId            int32                  `protobuf:"varint,1,opt,name=ad_id,json=adId,proto3" json:"ad_id,omitempty"`
	PredictedCtr    float64                `protobuf:"fixed64,2,opt,name=predicted_ctr,json=predictedCtr,proto3" json:"predicted_ctr,omitempty"`    // logistic regression output
	WeightedScore   float64                `protobuf:"fixed64,3,opt,name=weighted_score,json=weightedScore,proto3" json:"weighted_score,omitempty"` // CTR * bid_price — the auction ranking key
	RankPosition    int32                  `protobuf:"varint,4,opt,name=rank_position,json=rankPosition,proto3" json:"rank_position,omitempty"`
	ImpressionCount int32                  `protobuf:"varint,5,opt,name=impression_count,json=impressionCount,proto3" json:"impression_count,omitempty"`
	FromCache       bool                   `protobuf:"varint,6,opt,name=from_cache,json=fromCache,proto3" json:"from_cache,omitempty"` // true if served from 5s TTL cache
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RankedAd) Reset() {
	*x = RankedAd{}
	mi := &file_proto_ads_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RankedAd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankedAd) ProtoMessage() {}

func (x *RankedAd) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ads_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankedAd.ProtoReflect.Descriptor instead.
func (*RankedAd) Descriptor() ([]byte, []int) {
	return file_proto_ads_proto_rawDescGZIP(), []int{1}
}

func (x *RankedAd) GetAdId() int32 {
	if x != nil {
		return x.AdId
	}
	return 0
}

func (x *RankedAd) GetPredictedCtr() float64 {
	if x != nil {
		return x.PredictedCtr
	}
	return 0
}

func (x *RankedAd) GetWeightedScore() float64 {
	if x != nil {
		return x.WeightedScore
	}
	return 0
}

func (x *RankedAd) GetRankPosition() int32 {
	if x != nil {
		return x.RankPosition
	}
	return 0
}

func (x *RankedAd) GetImpressionCount() int32 {
	if x != nil {
		return x.ImpressionCount
	}
	return 0
}

func (x *RankedAd) GetFromCache() bool {
	if x != nil {
		return x.FromCache
	}
	return false
}

type RankAdsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ads           []*RankedAd            `protobuf:"bytes,1,rep,name=ads,proto3" json:"ads,omitempty"`
	LatencyUs     int64                  `protobuf:"varint,2,opt,name=latency_us,json=latencyUs,proto3" json:"latency_us,omitempty"`      // server-side latency in microseconds
	CacheStatus   string                 `protobuf:"bytes,3,opt,name=cache_status,json=cacheStatus,proto3" json:"cache_status,omitempty"` // "HIT" or "MISS"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RankAdsResponse) Reset() {
	*x = RankAdsResponse{}
	mi := &file_proto_ads_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RankAdsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankAdsResponse) ProtoMessage() {}

func (x *RankAdsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ads_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankAdsResponse.ProtoReflect.Descriptor instead.
func (*RankAdsResponse) Descriptor() ([]byte, []int) {
	return file_proto_ads_proto_rawDescGZIP(), []int{2}
}

func (x *RankAdsResponse) GetAds() []*RankedAd {
	if x != nil {
		return x.Ads
	}
	return nil
}

func (x *RankAdsResponse) GetLatencyUs() int64 {
	if x != nil {
		return x.LatencyUs
	}
	return 0
}

func (x *RankAdsResponse) GetCacheStatus() string {
	if x != nil {
		return x.CacheStatus
	}
	return ""
}

// ─── Stats (for React dashboard) ────────────────────────────────────────────
type StatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"` // how many ads to include
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsRequest) Reset() {
	*x = StatsRequest{}
	mi := &file_proto_ads_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRequest) ProtoMessage() {}

func (x *StatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ads_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsRequest.ProtoReflect.Descriptor instead.
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_ads_proto_rawDescGZIP(), []int{3}
}

func (x *StatsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type AdStat struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AdId            int32                  `protobuf:"varint,1,opt,name=ad_id,json=adId,proto3" json:"ad_id,omitempty"`
	PredictedCtr    float64                `protobuf:"fixed64,2,opt,name=predicted_ctr,json=predictedCtr,proto3" json:"predicted_ctr,omitempty"`
	WeightedScore   float64                `protobuf:"fixed64,3,opt,name=weighted_score,json=weightedScore,proto3" json:"weighted_score,omitempty"`
	RankPosition    int32                  `protobuf:"varint,4,opt,name=rank_position,json=rankPosition,proto3" json:"rank_position,omitempty"`
	ImpressionCount int32                  `protobuf:"varint,5,opt,name=impression_count,json=impressionCount,proto3" json:"impression_count,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AdStat) Reset() {
	*x = AdStat{}
	mi := &file_proto_ads_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdStat) ProtoMessage() {}

func (x *AdStat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ads_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdStat.ProtoReflect.Descriptor instead.
func (*AdStat) Descriptor() ([]byte, []int) {
	return file_proto_ads_proto_rawDescGZIP(), []int{4}
}

func (x *AdStat) GetAdId() int32 {
	if x != nil {
		return x.AdId
	}
	return 0
}

func (x *AdStat) GetPredictedCtr() float64 {
	if x != nil {
		return x.PredictedCtr
	}
	return 0
}

func (x *AdStat) GetWeightedScore() float64 {
	if x != nil {
		return x.WeightedScore
	}
	return 0
}

func (x *AdStat) GetRankPosition() int32 {
	if x != nil {
		return x.RankPosition
	}
	return 0
}

func (x *AdStat) GetImpressionCount() int32 {
	if x != nil {
		return x.ImpressionCount
	}
	return 0
}

type StatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         []*AdStat              `protobuf:"bytes,1,rep,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_proto_ads_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ads_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_ads_proto_rawDescGZIP(), []int{5}
}

func (x *StatsResponse) GetStats() []*AdStat {
	if x != nil {
		return x.Stats
	}
	return nil
}

var File_proto_ads_proto protoreflect.FileDescriptor

const file_proto_ads_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/ads.proto\x12\x03ads\"F\n" +
	"\x0eRankAdsRequest\x12\x13\n" +
	"\x05top_n\x18\x01 \x01(\x05R\x04topN\x12\x1f\n" +
	"\vcampaign_id\x18\x02 \x01(\x05R\n" +
	"campaignId\"\xda\x01\n" +
	"\bRankedAd\x12\x13\n" +
	"\x05ad_id\x18\x01 \x01(\x05R\x04adId\x12#\n" +
	"\rpredicted_ctr\x18\x02 \x01(\x01R\fpredictedCtr\x12%\n" +
	"\x0eweighted_score\x18\x03 \x01(\x01R\rweightedScore\x12#\n" +
	"\rrank_position\x18\x04 \x01(\x05R\frankPosition\x12)\n" +
	"\x10impression_count\x18\x05 \x01(\x05R\x0fimpressionCount\x12\x1d\n" +
	"\n" +
	"from_cache\x18\x06 \x01(\bR\tfromCache\"t\n" +
	"\x0fRankAdsResponse\x12\x1f\n" +
	"\x03ads\x18\x01 \x03(\v2\r.ads.RankedAdR\x03ads\x12\x1d\n" +
	"\n" +
	"latency_us\x18\x02 \x01(\x03R\tlatencyUs\x12!\n" +
	"\fcache_status\x18\x03 \x01(\tR\vcacheStatus\"$\n" +
	"\fStatsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"\xb9\x01\n" +
	"\x06AdStat\x12\x13\n" +
	"\x05ad_id\x18\x01 \x01(\x05R\x04adId\x12#\n" +
	"\rpredicted_ctr\x18\x02 \x01(\x01R\fpredictedCtr\x12%\n" +
	"\x0eweighted_score\x18\x03 \x01(\x01R\rweightedScore\x12#\n" +
	"\rrank_position\x18\x04 \x01(\x05R\frankPosition\x12)\n" +
	"\x10impression_count\x18\x05 \x01(\x05R\x0fimpressionCount\"2\n" +
	"\rStatsResponse\x12!\n" +
	"\x05stats\x18\x01 \x03(\v2\v.ads.AdStatR\x05stats2\x82\x01\n" +
	"\x10AdRankingService\x129\n" +
	"\fGetRankedAds\x12\x13.ads.RankAdsRequest\x1a\x14.ads.RankAdsResponse\x123\n" +
	"\n" +
	"GetAdStats\x12\x11.ads.StatsRequest\x1a\x12.ads.StatsResponseB\x10Z\x0eadranker/protob\x06proto3"

var (
	file_proto_ads_proto_rawDescOnce sync.Once
	file_proto_ads_proto_rawDescData []byte
)

func file_proto_ads_proto_rawDescGZIP() []byte {
	file_proto_ads_proto_rawDescOnce.Do(func() {
		file_proto_ads_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ads_proto_rawDesc), len(file_proto_ads_proto_rawDesc)))
	})
	return file_proto_ads_proto_rawDescData
}

var file_proto_ads_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_ads_proto_goTypes = []any{
	(*RankAdsRequest)(nil),  // 0: ads.RankAdsRequest
	(*RankedAd)(nil),        // 1: ads.RankedAd
	(*RankAdsResponse)(nil), // 2: ads.RankAdsResponse
	(*StatsRequest)(nil),    // 3: ads.StatsRequest
	(*AdStat)(nil),          // 4: ads.AdStat
	(*StatsResponse)(nil),   // 5: ads.StatsResponse
}
var file_proto_ads_proto_depIdxs = []int32{
	1, // 0: ads.RankAdsResponse.ads:type_name -> ads.RankedAd
	4, // 1: ads.StatsResponse.stats:type_name -> ads.AdStat
	0, // 2: ads.AdRankingService.GetRankedAds:input_type -> ads.RankAdsRequest
	3, // 3: ads.AdRankingService.GetAdStats:input_type -> ads.StatsRequest
	2, // 4: ads.AdRankingService.GetRankedAds:output_type -> ads.RankAdsResponse
	5, // 5: ads.AdRankingService.GetAdStats:output_type -> ads.StatsResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_ads_proto_init() }
func file_proto_ads_proto_init() {
	if File_proto_ads_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ads_proto_rawDesc), len(file_proto_ads_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ads_proto_goTypes,
		DependencyIndexes: file_proto_ads_proto_depIdxs,
		MessageInfos:      file_proto_ads_proto_msgTypes,
	}.Build()
	File_proto_ads_proto = out.File
	file_proto_ads_proto_goTypes = nil
	file_proto_ads_proto_depIdxs = nil
}
