// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: proto/ads.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AdRankingService_GetRankedAds_FullMethodName = "/ads.AdRankingService/GetRankedAds"
	AdRankingService_GetAdStats_FullMethodName   = "/ads.AdRankingService/GetAdStats"
)

// AdRankingServiceClient is the client API for AdRankingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ─── Service ────────────────────────────────────────────────────────────────
type AdRankingServiceClient interface {
	// GetRankedAds returns top-N ranked ads for an auction slot.
	// This is the hot path — served from cache when possible.
	GetRankedAds(ctx context.Context, in *RankAdsRequest, opts ...grpc.CallOption) (*RankAdsResponse, error)
	// GetAdStats returns per-ad CTR trends for the dashboard.
	GetAdStats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error)
}

type adRankingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdRankingServiceClient(cc grpc.ClientConnInterface) AdRankingServiceClient {
	return &adRankingServiceClient{cc}
}

func (c *adRankingServiceClient) GetRankedAds(ctx context.Context, in *RankAdsRequest, opts ...grpc.CallOption) (*RankAdsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RankAdsResponse)
	err := c.cc.Invoke(ctx, AdRankingService_GetRankedAds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adRankingServiceClient) GetAdStats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatsResponse)
	err := c.cc.Invoke(ctx, AdRankingService_GetAdStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdRankingServiceServer is the server API for AdRankingService service.
// All implementations must embed UnimplementedAdRankingServiceServer
// for forward compatibility.
//
// ─── Service ────────────────────────────────────────────────────────────────
type AdRankingServiceServer interface {
	// GetRankedAds returns top-N ranked ads for an auction slot.
	// This is the hot path — served from cache when possible.
	GetRankedAds(context.Context, *RankAdsRequest) (*RankAdsResponse, error)
	// GetAdStats returns per-ad CTR trends for the dashboard.
	GetAdStats(context.Context, *StatsRequest) (*StatsResponse, error)
	mustEmbedUnimplementedAdRankingServiceServer()
}

// UnimplementedAdRankingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdRankingServiceServer struct{}

func (UnimplementedAdRankingServiceServer) GetRankedAds(context.Context, *RankAdsRequest) (*RankAdsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRankedAds not implemented")
}
func (UnimplementedAdRankingServiceServer) GetAdStats(context.Context, *StatsRequest) (*StatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAdStats not implemented")
}
func (UnimplementedAdRankingServiceServer) mustEmbedUnimplementedAdRankingServiceServer() {}
func (UnimplementedAdRankingServiceServer) testEmbeddedByValue()                          {}

// UnsafeAdRankingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdRankingServiceServer will
// result in compilation errors.
type UnsafeAdRankingServiceServer interface {
	mustEmbedUnimplementedAdRankingServiceServer()
}

func RegisterAdRankingServiceServer(s grpc.ServiceRegistrar, srv AdRankingServiceServer) {
	// If the following call panics, it indicates UnimplementedAdRankingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdRankingService_ServiceDesc, srv)
}

func _AdRankingService_GetRankedAds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RankAdsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdRankingServiceServer).GetRankedAds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdRankingService_GetRankedAds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdRankingServiceServer).GetRankedAds(ctx, req.(*RankAdsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdRankingService_GetAdStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdRankingServiceServer).GetAdStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdRankingService_GetAdStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdRankingServiceServer).GetAdStats(ctx, req.(*StatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AdRankingService_ServiceDesc is the grpc.ServiceDesc for AdRankingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdRankingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ads.AdRankingService",
	HandlerType: (*AdRankingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRankedAds",
			Handler:    _AdRankingService_GetRankedAds_Handler,
		},
		{
			MethodName: "GetAdStats",
			Handler:    _AdRankingService_GetAdStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/ads.proto",
}
