version: "3.9"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: aduser
      POSTGRES_PASSWORD: adpass
      POSTGRES_DB: addb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./pipeline/schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  pgdata:
